import {BankAccount} from "./bank-account";
import {BourseAccount} from './bourse-account';

export class UserInfo {
  customerId: number;
  isLegal: number;
  bankAccounts: BankAccount[];
  domainIds: Array<number>;
  groupIds: Array<number>;
  bourseAccounts: BourseAccount[];
  customerStatusId: number;
  firstName: string;
  lastName: string;
  parent: string;
  birthDate: string;
  birthCertificationNumber: string;
  birthCertId: string;
  nationalCode: string;
  sexTypeId: number;
  phone: string;
  cellPhone: string;
  email: string;
  address: string;
  postalCode: string;
  isPortfo: number;
  isMmtpUser: number;
  mmtpUserStatusId: number;
  isSiteUser: number;
  eorderStatusId: number;
  mmtpUsername: string;
  creationDate: string;
  referredBy: string;
  cityCode: string;
  cityName: string;
  provinceCode: string;
  provinceName: string;
  smsTransaction: number;
  isEPaymentCustomer: number;
  sejamReferenceCode: string;
  dlNumber: string;
  bourseAccountName: string;
  accountNumber: string;
  issuingCity: string;
  hasSignSample: boolean;
  hasCustomerPhoto: boolean;
  hasBirthCertificate: boolean;
  hasCertificateComments: boolean;
  hasZipFile: boolean;
  fullName: string;
  sexTypeName: string;
}
